---
- name: Deploy App
  hosts: ec2
  gather_facts: no
  tasks:
    - name: Remove old container
      shell: docker rm -f pipeline_container222 || true

    - name: Pull latest image
      shell: docker pull nilesh9890/pipeline7:latest

    - name: Run container
      shell: docker run -d -p 5003:5002 --name pipeline_container222 --restart unless-stopped nilesh9890/pipeline7:latest   #restart unless stoped = restart automaticaly container after instance start /or crashes